### ISSUE TITLE
Prototype of Limitless 

### ISSUE THREAD

**Issue by petergault** [empirical-org/QuillLimitless#1]
![screen shot 2015-12-23 at 1 59 27 pm](https://cloud.githubusercontent.com/assets/3667179/11982919/681357c4-a97d-11e5-834f-9963db5b7a34.png)

- [x] Peter will generate a CSV of 24 practice questions. 
- [x] Display the words, and they will be tappable via parslet or some other solution. 
- [x] If you tap the right word, you get one point
- [x] a text box then pops up. If you input the right word (validates in the curley brackets) you get another point. 
- [ ] It serves one question per concept, and goes through all 4 before returning to the original.

**Comment by petergault** [comment]
# Prototype Data set: 
[Limitless Prototype Dataset.xlsx](https://github.com/empirical-org/QuillLimitless/files/71220/Limitless.Prototype.Dataset.xlsx)


CSV is not supported, but you can find it in slack.

**Comment by ddmck** [comment]
- [ ] Throw on firebase with a play screen. (Welcome to Limitless etc)
- [ ] Loading data from firebase api rather than JSON files 
- [ ] Start with question one and keeps on going.
- [ ] Results modal for checking progress/performance
- [ ] Device lab testing. Focus on Android devices.
- [ ] Use commonly confused as a play testing data set.
- [ ] Incorporate David Cameron "Britishness" test.
 
After returning from Scotland
- [ ] implement design
- [ ] Incorporate SEO feedback into Diagnostic.
